### ISSUE TITLE
JAZZ INSTALLATION ERROR :Requesting your assistance

### ISSUE THREAD

**Issue by nikhil613** [tmobile/jazz#63] opened 2017-12-21 12:01 UTC
### Description

[An error is generated when I try to install jazz framework. When I run the installation process, after providing Jenkins details and credentials throws a critical error as follows:
Traceback (most recent call last):
  File "./run.py", line 86, in <module>
    if check_jenkins_user(jenkinsServerELB, jenkinsuser, jenkinspasswd):
  File "./run.py", line 50, in check_jenkins_user
    os.remove('jenkins-cli.jar')
OSError: [Errno 2] No such file or directory: 'jenkins-cli.jar' 
  
Can you help me define what this error means and why it is shown? Also I was unable to find a documentation to help us through the possible errors during the installation, Please help me out in this regard along with this issue's resolution if you can.
]
### Steps to Reproduce

1. Run the jazz installation process
2.  After finishing certain amount of downloads, It asks for jenkins URL, I have provided the valid jenkins URL
3. Then asks for tag name to prefix your stack, I provided the name.
4. After that I gave the username and password. It threw the error mentioned in description

**Expected behavior:** [Go to next step of installation]

**Actual behavior:** [Threw an OS error]

**Reproduces how often:** [It never went past it even after multiple tries with difference details and credentials]

### Additional Information
I have setup a Jenkins server with an instance as specified in jazz installation guide in github wiki. I tested it and it works without any problem. 
I opened the run.py to investigate and tried changing the hard coded port number but still no change.
 
**Do ask me for any details you want in extra**

**Comment by suryajak** [comment] 2017-12-21 19:10
Can you specify version you were trying to install?

**Comment by nikhil613** [comment] 2017-12-22 06:24
I dont know the version as i couldnt find a version number on the jazz installer or anywhere. It should be the latest. I just ran this code:-
 curl -L https://raw.githubusercontent.com/tmobile/jazz-installer/master/installscripts/terraforminstaller/rhel7Installer.sh -o rhel7Installer.sh && chmod +x rhel7Installer.sh && ./rhel7Installer.sh master && cd ./jazz-installer/installscripts/wizard && ./run.py

**Comment by Feroz-Shaikh** [comment] 2017-12-22 06:27
Thanks @nikhil613. We will try to reproduce the error now and take it from there.

**Comment by Feroz-Shaikh** [comment] 2017-12-22 09:16
This is a bug in the error use-case of the installer due to the way it behaves. This is actually fixed in the upcoming release of v1.1.3. However, as a quick fix I have created the fix branch https://github.com/tmobile/jazz-installer/tree/v1.1.2_fix for the same. Thanks for confirming that you went past the error. Great Things coming up on v1.1.3 release. Stay tuned!

**Comment by suryajak** [comment] 2017-12-22 19:54
@nikhil613: Let us know if you are up and running. If not please apply the fix in branch cited above and let us know if its fixed

**Comment by nikhil613** [comment] 2017-12-23 10:36
Yes it is fixed.

**Closed** 2018-01-02 06:06 UTC
Labels: bug
